---
- name: Set up a software repository
  hosts: all
  gather_facts: False
  tasks:
    - name: Import the gpg key
      rpm_key:
        state: present
        key: http://repo.mysql.com/RPM-GPG-KEY-mysql
    - name: Create the repository
      yum_repository:
        name: mysql180-community
        description: "MySQL 8.0 YUM Repo"
        baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/
        gpgcheck: True
        gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
        enabled: True
