---
- name: working with partitioning and lvm
  hosts: all
  gather_facts: False
  tasks:
    - name: create a partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 800MB
    - name: create vg_database volume group
      lvg:
        vg: vg_database
        pvs: /dev/sdb
    - name: create logical volume
      lvol:
        lv: lv_mysql
        vg: vg_database
        size: 512
    - name: create xfs filesystem
      filesystem:
        dev: /dev/vg_database/lv_mysql
        fstype: xfs
    - name: create mount dir
      file:
        path: /mnt/mysql_backups
        state: directory
    - name: mount the lv to /mnt/mysql_backups
      mount:
        path: /mnt/mysql_backups
        state: mounted
        src: /dev/vg_database/lv_mysql
        fstype: xfs





