---   
- name: Manage SELinux fcontext
  hosts: webservers
  tasks:
    - name: Create webdev user
      user:
        name: webdev
        state: present
    - name: Create webdev dir
      file:
        path: /webdev
        state: directory
        owner: webdev
        mode: '2775'
        setype: httpd_sys_content_t
    - name: Create link
      file:
        path: /var/www/html/webdev
        src: /webdev
        state: link
        force: True
    - name: Create index file
      copy:
        content: "Webservers"
        dest: /webdev/index.html
        setype: httpd_sys_content_t
    - name: Start httpd and firewalld services
      service:
        name: "{{ item }}"
        state: started
        enabled: True
      loop:
        - httpd
        - firewalld
    - name: Start httpd and firewalld services
      service:
        name: "{{ item }}"
        state: started
        enabled: True
      loop:
        - httpd
        - firewalld
    - name: Open port 80 and 443
      firewalld:
        port: "{{ item }}"
        state: enabled
        immediate: True
        permanent: True
      loop:
        - 80/tcp
        - 443/tcp
